version: '3.8'
services:
    postgres:
        image: postgres:latest
        container_name: "postgres"
        env_file: "postgres.env"
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    server:
        image: golang:latest
        container_name: "server"
        env_file: "postgres.env"
        ports:
            - "3000:3000"
        volumes:
            - ./gocode:/gocode
        working_dir: /gocode
        command: go run main.go
        links:
            - postgres
